### ISSUE TITLE
Variables in Experiment Reload Not Working

### ISSUE THREAD

**Issue by ladydanger** [team-melbourne-rgsoc2015/discourse-adsense-test#7]
Hi Coach!

We've got a branch called, ExperimentReload (see link below), that reloads the ad based on a change of page in Discourse via their Discourse.PageTracker.

https://github.com/team-melbourne-rgsoc2015/discourse-adsense-test/blob/ExperimentReload/assets/javascripts/discourse/components/google-adsense.js.es6#L1-L5

The code is working fine when we hardcode in ad_width, ad_height and ad_code global variables, however, the reload function that is within the Discourse.Pagetracker function doesn't seem to be functioning and changing the variables based on the user inputs in SiteSettings.

We feel that it may be a javascript precendence thing with variables that creating this problem in this file discourse-adsense-test/assets/javascripts/discourse/components/google-adsense.js.es6, and your help would be greatly appreciated.

I've just created a separate issue here as opposed to adding to the PR because this is a separate issue, but if you want to make changes, please feel free to make changes directly to https://github.com/team-melbourne-rgsoc2015/discourse-adsense-test/pull/5

Thanks a million!

**Comment by eviltrout** [comment]
When I tried it locally I didn't see any variables conflicting so I am a little skeptical if that is the cause.

I do think what you might have to do is take the working plugin and change it one step at a time into your component version until you figure out the step that breaks it. It's nasty annoying work but at some point you will likely figure out the difference!

**Comment by snjqi188** [comment]
aye, makes sense. perhaps my hypothesis on variable precedence might not be correct. thanks and we will try that out!

**Comment by ladydanger** [comment]
Hi @eviltrout,
Closing this issue now b/c Sarah refactored the code and all is working fine :-)
Thanks mate!
